spring:
  application:
    name: eureka-discovery-service

server:
  port: 9001
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9001/eureka
